name: first

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Compile using rustc
        run: rustc src/main.rs

      - name: run tests
        run: cargo test

      - name: deploy to Heroku
        run: echo "Deploy"
