name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repo"
        uses: actions/checkout@v3

      - name: "Compiling the application"
        run: rustc main.rs
      
      - name: "Tests "
        run: cargo test
